// This file was generated by the WebGME Federates Exporter plugin. Do not edit manually!

/*
 * Copyright (c) 2008, Institute for Software Integrated Systems, Vanderbilt University
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 *
 * IN NO EVENT SHALL THE VANDERBILT UNIVERSITY BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE VANDERBILT
 * UNIVERSITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * THE VANDERBILT UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE VANDERBILT UNIVERSITY HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 */

/*
 * 	NOTE:  ALL "if" STATEMENTS IN THIS CODE THAT HAD THE FORM:
 *
 *  if (condition) statement;
 *
 *	OR
 *
 *  if (condition) statement1;
 *  else           statement2;
 *
 *  HAVE BEEN CONVERTED TO THE FORMS:
 *
 *  if (condition) {
 *		statement;
 *	}
 *
 *	AND
 *
 *  if (condition) {
 *		statement1;
 *	} else {
 *		statement2;
 *	}
 *
 *	RESPECTIVELY.  THIS IS BECAUSE THE OMNET DEBUGGER APPEARS TO HAVE A PROBLEM
 *  WITH THE NON-BRACED FORMS OF THE IF STATEMENT.  *PLEASE* DO NOT CHANGE IT BACK.
 *  -- H.S.N.
 *
 */

#ifndef _ChallengeObject_CLASS
#define _ChallengeObject_CLASS

#include "ParentObject.hpp"
#include "C2WException.hpp"

#include <boost/unordered_set.hpp>

class ChallengeObject : public ParentObject {
public:
	typedef ParentObject Super;
	typedef boost::shared_ptr< ChallengeObject > SP;

	static StringVector get_attribute_names() {
		return getDatamemberNames();
	}

	static StringVector get_all_attribute_names() {
		return getAllDatamemberNames();
	}

	ChallengeObject( void ) { }

	static SP create( void ) { return SP( new ChallengeObject ); }

private:
	static boost::unordered_set< std::string > m_publishedAttributeNames;

	static int &get_beginIndex_handle_var( void ) {
		static int beginIndex_handle;
		return beginIndex_handle;
	}

	static int &get_challengeId_handle_var( void ) {
		static int challengeId_handle;
		return challengeId_handle;
	}

	static int &get_stringValue_handle_var( void ) {
		static int stringValue_handle;
		return stringValue_handle;
	}

public:
	static int get_beginIndex_handle( void ) { return get_beginIndex_handle_var(); }
	static int get_challengeId_handle( void ) { return get_challengeId_handle_var(); }
	static int get_stringValue_handle( void ) { return get_stringValue_handle_var(); }

private:
	static int &getHandle( void ) {
		static int handle;
		return handle;
	}

public:
	static int get_handle( void ) { return getHandle(); }
	static std::string get_class_name( void ) { return "ChallengeObject"; }

private:
	static StringVector &getDatamemberNames( void ) {
		static StringVector datamemberNames;
		return datamemberNames;
	}

	static StringVector &getAllDatamemberNames( void ) {
		static StringVector allDatamemberNames;
		return allDatamemberNames;
	}

private:
	static RTI::AttributeHandleSet &getPublishedAttributeHandleSet_var( void ) {
		static RTI::AttributeHandleSet *publishedAttributeHandleSetPtr = RTI::AttributeHandleSetFactory::create( 3 );
		return *publishedAttributeHandleSetPtr;
	}
	static StringVector &getPublishAttributeNameVector( void ) {
		static StringVector publishAttributeNameVector;
		return publishAttributeNameVector;
	}

	static RTI::AttributeHandleSet &getSubscribedAttributeHandleSet_var( void ) {
		static RTI::AttributeHandleSet *subscribedAttributeHandleSet = RTI::AttributeHandleSetFactory::create( 3 );
		return *subscribedAttributeHandleSet;
	}
	static StringVector &getSubscribeAttributeNameVector( void ) {
		static StringVector subscribeAttributeNameVector;
		return subscribeAttributeNameVector;
	}

private:
	static ObjectRoot::SP factory( void ) {
		return ObjectRoot::SP( new ChallengeObject() );
	}

	static std::string &getInitErrorMessage( void ) {
		static std::string initErrorMessage( "Error:  ChallengeObject:  could not initialize:  " );
		return initErrorMessage;
	}

protected:
	static void init( RTI::RTIambassador *rti );

private:
	static bool &getIsPublished( void ) {
		static bool isPublished = false;
		return isPublished;
	}

	static std::string &getPublishErrorMessage( void ) {
		static std::string publishErrorMessage = "Error:  ChallengeObject:  could not publish:  ";
		return publishErrorMessage;
	}

public:
	static void publish( RTI::RTIambassador *rti );

private:
	static std::string &getUnpublishErrorMessage( void ) {
		static std::string unpublishErrorMessage = "Error:  ChallengeObject:  could not unpublish:  ";
		return unpublishErrorMessage;
	}

public:
	static void unpublish( RTI::RTIambassador *rti );

private:
	static bool &getIsSubscribed( void ) {
		static bool isSubscribed = false;
		return isSubscribed;
	}
	static std::string &getSubscribeErrorMessage( void ) {
		static std::string subscribedErrorMessage = "Error:  ChallengeObject:  could not subscribe:  ";
		return subscribedErrorMessage;
	}

public:
	static void subscribe( RTI::RTIambassador *rti );

private:
	static std::string getUnsubscribeErrorMessage( void ) {
		static std::string unsubscribeErrorMessage = "Error:  ChallengeObject:  could not unsubscribe:  ";
		return unsubscribeErrorMessage;
	}

public:
	static void unsubscribe( RTI::RTIambassador *rti );

	static bool static_init( void );

	static bool match( int handle ) { return handle == get_handle(); }

	virtual int getClassHandle( void ) const { return get_handle(); }
	virtual std::string getClassName( void ) const { return get_class_name(); }
	virtual StringVector getAttributeNames( void ) const { return get_attribute_names(); }
	virtual StringVector getAllAttributeNames( void ) const { return get_all_attribute_names(); }

	virtual std::string getAttributeName( int datamemberHandle ) const {
		if (datamemberHandle == get_beginIndex_handle()) {
			return std::string("beginIndex");
		} else if (datamemberHandle == get_challengeId_handle()) {
			return std::string("challengeId");
		} else if (datamemberHandle == get_stringValue_handle()) {
			return std::string("stringValue");
		} else {
			return ParentObject::getAttributeName(datamemberHandle);
		}
	}

	virtual void publishObject( RTI::RTIambassador *rti ) { publish( rti ); }
	virtual void subscribeObject( RTI::RTIambassador *rti ) { subscribe( rti ); }

	virtual ObjectRoot::SP clone( void ) {
		return ObjectRoot::SP(  new ChallengeObject( *this )  );
	}

	virtual const RTI::AttributeHandleSet &getSubscribedAttributeHandleSet( void ) { return getSubscribedAttributeHandleSet_var(); }

public:
	static void publish_beginIndex( void ) {
		getPublishAttributeNameVector().push_back( "beginIndex" );
		m_publishedAttributeNames.emplace( "beginIndex" );
	}

	static void unpublish_beginIndex( void ) {
		getPublishAttributeNameVector().erase( std::remove( getPublishAttributeNameVector().begin(), getPublishAttributeNameVector().end(), "beginIndex" ), getPublishAttributeNameVector().end() );
		m_publishedAttributeNames.erase( "beginIndex" );
	}

	static void subscribe_beginIndex( void ) {
		getSubscribeAttributeNameVector().push_back( "beginIndex" );
	}

	static void unsubscribe_beginIndex(void ) {
		getSubscribeAttributeNameVector().erase( std::remove( getSubscribeAttributeNameVector().begin(), getSubscribeAttributeNameVector().end(), "beginIndex" ), getSubscribeAttributeNameVector().end() );
	}

	static void publish_challengeId( void ) {
		getPublishAttributeNameVector().push_back( "challengeId" );
		m_publishedAttributeNames.emplace( "challengeId" );
	}

	static void unpublish_challengeId( void ) {
		getPublishAttributeNameVector().erase( std::remove( getPublishAttributeNameVector().begin(), getPublishAttributeNameVector().end(), "challengeId" ), getPublishAttributeNameVector().end() );
		m_publishedAttributeNames.erase( "challengeId" );
	}

	static void subscribe_challengeId( void ) {
		getSubscribeAttributeNameVector().push_back( "challengeId" );
	}

	static void unsubscribe_challengeId(void ) {
		getSubscribeAttributeNameVector().erase( std::remove( getSubscribeAttributeNameVector().begin(), getSubscribeAttributeNameVector().end(), "challengeId" ), getSubscribeAttributeNameVector().end() );
	}

	static void publish_stringValue( void ) {
		getPublishAttributeNameVector().push_back( "stringValue" );
		m_publishedAttributeNames.emplace( "stringValue" );
	}

	static void unpublish_stringValue( void ) {
		getPublishAttributeNameVector().erase( std::remove( getPublishAttributeNameVector().begin(), getPublishAttributeNameVector().end(), "stringValue" ), getPublishAttributeNameVector().end() );
		m_publishedAttributeNames.erase( "stringValue" );
	}

	static void subscribe_stringValue( void ) {
		getSubscribeAttributeNameVector().push_back( "stringValue" );
	}

	static void unsubscribe_stringValue(void ) {
		getSubscribeAttributeNameVector().erase( std::remove( getSubscribeAttributeNameVector().begin(), getSubscribeAttributeNameVector().end(), "stringValue" ), getSubscribeAttributeNameVector().end() );
	}

protected:
	Attribute< int, int > _beginIndex;
	Attribute< int, std::string > _stringValue;

public:
	void set_beginIndex( int beginIndex ) {
		_beginIndex.setValue( beginIndex );
		_beginIndex.setTime( getTime() );
	}

	int get_beginIndex( void ) const {
		return _beginIndex.getValue();
	}

	double get_beginIndex_time( void ) {
		return _beginIndex.getTime();
	}

	void set_stringValue( const std::string & stringValue ) {
		_stringValue.setValue( stringValue );
		_stringValue.setTime( getTime() );
	}

	const std::string & get_stringValue( void ) const {
		return _stringValue.getValue();
	}

	double get_stringValue_time( void ) {
		return _stringValue.getTime();
	}

	ChallengeObject( const RTI::AttributeHandleValuePairSet &datamemberMap ) : Super( datamemberMap ) { }

	ChallengeObject( const RTI::AttributeHandleValuePairSet &datamemberMap, const RTIfedTime &logicalTime ) : Super( datamemberMap, logicalTime ) { }

public:
	TypeMedley getAttribute( const std::string &datamemberName ) const {
		if ( "beginIndex" == datamemberName ) {
			return TypeMedley( get_beginIndex() );
		} else if ( "stringValue" == datamemberName ) {
			return TypeMedley( get_stringValue() );
		} else {
			return Super::getAttribute( datamemberName );
		}
	}

protected:
	virtual bool setAttributeAux( const std::string &datamemberName, const std::string &val ) {
		bool retval = true;
		if ( "beginIndex" == datamemberName ) {
			set_beginIndex(  TypeMedley( val )  );
		} else if ( "stringValue" == datamemberName ) {
			set_stringValue(  TypeMedley( val )  );
		} else {
			retval = Super::setAttributeAux( datamemberName, val );
		}

		return retval;
	}

	virtual bool setAttributeAux( const std::string &datamemberName, const TypeMedley &val ) {
		bool retval = true;
		if ( "beginIndex" == datamemberName ) {
			set_beginIndex( val );
		} else if ( "stringValue" == datamemberName ) {
			set_stringValue( val );
		} else {
			retval = Super::setAttributeAux( datamemberName, val );
		}

		return retval;
	}

	virtual AttributeHandleValuePairSetSP createDatamemberHandleValuePairSet( bool force );
};

typedef ChallengeObject::SP ChallengeObjectSP;

static bool call_ChallengeObject_static_init = ChallengeObject::static_init();

std::ostream &operator<<( std::ostream &os, ChallengeObject::SP entitySP );
std::ostream &operator<<( std::ostream &os, const ChallengeObject &entity );

#endif
