// This file was generated by the WebGME Federates Exporter plugin. Do not edit manually!

/*
 * Copyright (c) 2008, Institute for Software Integrated Systems, Vanderbilt University
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 *
 * IN NO EVENT SHALL THE VANDERBILT UNIVERSITY BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE VANDERBILT
 * UNIVERSITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * THE VANDERBILT UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE VANDERBILT UNIVERSITY HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 */

/*
 * 	NOTE:  ALL "if" STATEMENTS IN THIS CODE THAT HAD THE FORM:
 *
 *  if (condition) statement;
 *
 *	OR
 *
 *  if (condition) statement1;
 *  else           statement2;
 *
 *  HAVE BEEN CONVERTED TO THE FORMS:
 *
 *  if (condition) {
 *		statement;
 *	}
 *
 *	AND
 *
 *  if (condition) {
 *		statement1;
 *	} else {
 *		statement2;
 *	}
 *
 *	RESPECTIVELY.  THIS IS BECAUSE THE OMNET DEBUGGER APPEARS TO HAVE A PROBLEM
 *  WITH THE NON-BRACED FORMS OF THE IF STATEMENT.  *PLEASE* DO NOT CHANGE IT BACK.
 *  -- H.S.N.
 *
 */

#ifndef _Response_CLASS
#define _Response_CLASS

#include "ParentInteraction.hpp"
#include "C2WException.hpp"

class Response : public ParentInteraction {
public:
	typedef ParentInteraction Super;
	typedef boost::shared_ptr< Response > SP;

	static StringVector get_parameter_names() {
		return getDatamemberNames();
	}

	static StringVector get_all_parameter_names() {
		return getAllDatamemberNames();
	}

	Response( void ) { }

	static SP create( void ) { return SP( new Response ); }

private:
	static int &get_actualLogicalGenerationTime_handle_var( void ) {
		static int actualLogicalGenerationTime_handle;
		return actualLogicalGenerationTime_handle;
	}

	static int &get_challengeId_handle_var( void ) {
		static int challengeId_handle;
		return challengeId_handle;
	}

	static int &get_federateFilter_handle_var( void ) {
		static int federateFilter_handle;
		return federateFilter_handle;
	}

	static int &get_originFed_handle_var( void ) {
		static int originFed_handle;
		return originFed_handle;
	}

	static int &get_sourceFed_handle_var( void ) {
		static int sourceFed_handle;
		return sourceFed_handle;
	}

	static int &get_substring_handle_var( void ) {
		static int substring_handle;
		return substring_handle;
	}

public:
	static int get_actualLogicalGenerationTime_handle( void ) { return get_actualLogicalGenerationTime_handle_var(); }
	static int get_challengeId_handle( void ) { return get_challengeId_handle_var(); }
	static int get_federateFilter_handle( void ) { return get_federateFilter_handle_var(); }
	static int get_originFed_handle( void ) { return get_originFed_handle_var(); }
	static int get_sourceFed_handle( void ) { return get_sourceFed_handle_var(); }
	static int get_substring_handle( void ) { return get_substring_handle_var(); }

private:
	static int &getHandle( void ) {
		static int handle;
		return handle;
	}

public:
	static int get_handle( void ) { return getHandle(); }
	static std::string get_class_name( void ) { return "Response"; }

private:
	static StringVector &getDatamemberNames( void ) {
		static StringVector datamemberNames;
		return datamemberNames;
	}

	static StringVector &getAllDatamemberNames( void ) {
		static StringVector allDatamemberNames;
		return allDatamemberNames;
	}

private:
	static InteractionRoot::SP factory( void ) {
		return InteractionRoot::SP( new Response() );
	}

	static std::string &getInitErrorMessage( void ) {
		static std::string initErrorMessage( "Error:  Response:  could not initialize:  " );
		return initErrorMessage;
	}

protected:
	static void init( RTI::RTIambassador *rti );

private:
	static bool &getIsPublished( void ) {
		static bool isPublished = false;
		return isPublished;
	}

	static std::string &getPublishErrorMessage( void ) {
		static std::string publishErrorMessage = "Error:  Response:  could not publish:  ";
		return publishErrorMessage;
	}

public:
	static void publish( RTI::RTIambassador *rti );

private:
	static std::string &getUnpublishErrorMessage( void ) {
		static std::string unpublishErrorMessage = "Error:  Response:  could not unpublish:  ";
		return unpublishErrorMessage;
	}

public:
	static void unpublish( RTI::RTIambassador *rti );

private:
	static bool &getIsSubscribed( void ) {
		static bool isSubscribed = false;
		return isSubscribed;
	}
	static std::string &getSubscribeErrorMessage( void ) {
		static std::string subscribedErrorMessage = "Error:  Response:  could not subscribe:  ";
		return subscribedErrorMessage;
	}

public:
	static void subscribe( RTI::RTIambassador *rti );

private:
	static std::string getUnsubscribeErrorMessage( void ) {
		static std::string unsubscribeErrorMessage = "Error:  Response:  could not unsubscribe:  ";
		return unsubscribeErrorMessage;
	}

public:
	static void unsubscribe( RTI::RTIambassador *rti );

	static bool static_init( void );

	static bool match( int handle ) { return handle == get_handle(); }

	virtual int getClassHandle( void ) const { return get_handle(); }
	virtual std::string getClassName( void ) const { return get_class_name(); }
	virtual StringVector getParameterNames( void ) const { return get_parameter_names(); }
	virtual StringVector getAllParameterNames( void ) const { return get_all_parameter_names(); }

	virtual std::string getParameterName( int datamemberHandle ) const {
		if (datamemberHandle == get_actualLogicalGenerationTime_handle()) {
			return std::string("actualLogicalGenerationTime");
		} else if (datamemberHandle == get_challengeId_handle()) {
			return std::string("challengeId");
		} else if (datamemberHandle == get_federateFilter_handle()) {
			return std::string("federateFilter");
		} else if (datamemberHandle == get_originFed_handle()) {
			return std::string("originFed");
		} else if (datamemberHandle == get_sourceFed_handle()) {
			return std::string("sourceFed");
		} else if (datamemberHandle == get_substring_handle()) {
			return std::string("substring");
		} else {
			return ParentInteraction::getParameterName(datamemberHandle);
		}
	}

	virtual void publishInteraction( RTI::RTIambassador *rti ) { publish( rti ); }
	virtual void subscribeInteraction( RTI::RTIambassador *rti ) { subscribe( rti ); }

	virtual InteractionRoot::SP clone( void ) {
		return InteractionRoot::SP(  new Response( *this )  );
	}

private:
	std::string _substring;

public:
	void set_substring( const std::string & substring ) { _substring = substring; }

	const std::string & get_substring( void ) const { return _substring; }

	Response( const RTI::ParameterHandleValuePairSet &datamemberMap ) : Super( datamemberMap ) { }

	Response( const RTI::ParameterHandleValuePairSet &datamemberMap, const RTIfedTime &logicalTime ) : Super( datamemberMap, logicalTime ) { }

public:
	TypeMedley getParameter( const std::string &datamemberName ) const {
		if ( "substring" == datamemberName ) {
			return TypeMedley( get_substring() );
		} else {
			return Super::getParameter( datamemberName );
		}
	}

protected:
	virtual bool setParameterAux( const std::string &datamemberName, const std::string &val ) {
		bool retval = true;
		if ( "substring" == datamemberName ) {
			set_substring(  TypeMedley( val )  );
		} else {
			retval = Super::setParameterAux( datamemberName, val );
		}

		return retval;
	}

	virtual bool setParameterAux( const std::string &datamemberName, const TypeMedley &val ) {
		bool retval = true;
		if ( "substring" == datamemberName ) {
			set_substring( val );
		} else {
			retval = Super::setParameterAux( datamemberName, val );
		}

		return retval;
	}
};

typedef Response::SP ResponseSP;

static bool call_Response_static_init = Response::static_init();

std::ostream &operator<<( std::ostream &os, Response::SP entitySP );
std::ostream &operator<<( std::ostream &os, const Response &entity );

#endif
