// This file was generated by the WebGME Federates Exporter plugin. Do not edit manually!

package ZoneProject;

import java.util.HashSet;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.cpswt.utils.CpswtUtils;

import hla.rti.AttributeHandleSet;
import hla.rti.FederateNotExecutionMember;
import hla.rti.LogicalTime;
import hla.rti.NameNotFound;
import hla.rti.ObjectClassNotDefined;
import hla.rti.ObjectClassNotPublished;
import hla.rti.ObjectClassNotSubscribed;
import hla.rti.RTIambassador;
import hla.rti.ReflectedAttributes;
import hla.rti.SuppliedAttributes;

import org.cpswt.hla.*;

/**
* Implements ObjectRoot.ControllerState
*/
public class ControllerState extends ObjectRoot {

    private static final Logger logger = LogManager.getLogger();

    /**
    * Creates an instance of the ControllerState object class with default attribute values.
    */
    public ControllerState() {}

    private static int _DamperPostionPct_handle;
    private static int _ZoneName_handle;

    private static boolean _isInitialized = false;

    private static int _handle;

    /**
    * Returns the handle (RTI assigned) of the ControllerState object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return the handle of the class pertaining to the reference,
    * rather than the handle of the class for the instance referred to by the reference.
    * For the polymorphic version of this method, use {@link #getClassHandle()}.
    *
    * @return the RTI assigned integer handle that represents this object class
    */
    public static int get_handle() {
        return _handle;
    }

    /**
    * Returns the fully-qualified (dot-delimited) name of the ControllerState object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return the name of the class pertaining to the reference,
    * rather than the name of the class for the instance referred to by the reference.
    * For the polymorphic version of this method, use {@link #getClassName()}.
    *
    * @return the fully-qualified HLA class path for this object class
    */
    public static String get_class_name() {
        return "ObjectRoot.ControllerState";
    }

    /**
    * Returns the simple name (the last name in the dot-delimited fully-qualified
    * class name) of the ControllerState object class.
    *
    * @return the name of this object class
    */
    public static String get_simple_class_name() {
        return "ControllerState";
    }

    private static Set< String > _datamemberNames = new HashSet< String >();
    private static Set< String > _allDatamemberNames = new HashSet< String >();

    /**
    * Returns a set containing the names of all of the non-hidden attributes in the
    * ControllerState object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return a set of parameter names pertaining to the reference,
    * rather than the parameter names of the class for the instance referred to by
    * the reference.  For the polymorphic version of this method, use
    * {@link #getAttributeNames()}.
    *
    * @return a modifiable set of the non-hidden attribute names for this object class
    */
    public static Set< String > get_attribute_names() {
        return new HashSet< String >(_datamemberNames);
    }

    /**
    * Returns a set containing the names of all of the attributes in the
    * ControllerState object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return a set of parameter names pertaining to the reference,
    * rather than the parameter names of the class for the instance referred to by
    * the reference.  For the polymorphic version of this method, use
    * {@link #getAttributeNames()}.
    *
    * @return a modifiable set of the attribute names for this object class
    */
    public static Set< String > get_all_attribute_names() {
        return new HashSet< String >(_allDatamemberNames);
    }

    private static Set< String > _publishAttributeNameSet = new HashSet< String >();
    private static Set< String > _subscribeAttributeNameSet = new HashSet< String >();

    static {
        _classNameSet.add("ObjectRoot.ControllerState");
        _classNameClassMap.put("ObjectRoot.ControllerState", ControllerState.class);

        _datamemberClassNameSetMap.put("ObjectRoot.ControllerState", _datamemberNames);
        _allDatamemberClassNameSetMap.put("ObjectRoot.ControllerState", _allDatamemberNames);

        _datamemberNames.add("DamperPostionPct");
        _datamemberNames.add("ZoneName");

        _datamemberTypeMap.put("DamperPostionPct", "int");
        _datamemberTypeMap.put("ZoneName", "String");

        _allDatamemberNames.add("DamperPostionPct");
        _allDatamemberNames.add("ZoneName");

        _classNamePublishAttributeNameMap.put("ObjectRoot.ControllerState", _publishAttributeNameSet);
        _classNameSubscribeAttributeNameMap.put("ObjectRoot.ControllerState", _subscribeAttributeNameSet);
    }

    protected static void init(RTIambassador rti) {
        if (_isInitialized) return;
        _isInitialized = true;

        ObjectRoot.init(rti);

        boolean isNotInitialized = true;
        while(isNotInitialized) {
            try {
                _handle = rti.getObjectClassHandle("ObjectRoot.ControllerState");
                isNotInitialized = false;
            } catch (FederateNotExecutionMember e) {
                logger.error("could not initialize: Federate Not Execution Member", e);
                return;
            } catch (NameNotFound e) {
                logger.error("could not initialize: Name Not Found", e);
                return;
            } catch (Exception e) {
                logger.error(e);
                CpswtUtils.sleepDefault();
            }
        }

        _classNameHandleMap.put("ObjectRoot.ControllerState", get_handle());
        _classHandleNameMap.put(get_handle(), "ObjectRoot.ControllerState");
        _classHandleSimpleNameMap.put(get_handle(), "ControllerState");

        isNotInitialized = true;
        while(isNotInitialized) {
            try {
                _DamperPostionPct_handle = rti.getAttributeHandle("DamperPostionPct", get_handle());
                _ZoneName_handle = rti.getAttributeHandle("ZoneName", get_handle());
                isNotInitialized = false;
            } catch (FederateNotExecutionMember e) {
                logger.error("could not initialize: Federate Not Execution Member", e);
                return;
            } catch (ObjectClassNotDefined e) {
                logger.error("could not initialize: Object Class Not Defined", e);
                return;
            } catch (NameNotFound e) {
                logger.error("could not initialize: Name Not Found", e);
                return;
            } catch (Exception e) {
                logger.error(e);
                CpswtUtils.sleepDefault();
            }
        }

        _datamemberNameHandleMap.put("ObjectRoot.ControllerState.DamperPostionPct", _DamperPostionPct_handle);
        _datamemberNameHandleMap.put("ObjectRoot.ControllerState.ZoneName", _ZoneName_handle);

        _datamemberHandleNameMap.put(_DamperPostionPct_handle, "DamperPostionPct");
        _datamemberHandleNameMap.put(_ZoneName_handle, "ZoneName");
    }

    private static boolean _isPublished = false;

    /**
    * Publishes the ControllerState object class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void publish(RTIambassador rti) {
        if (_isPublished) return;

        init(rti);

        AttributeHandleSet publishedAttributeHandleSet = _factory.createAttributeHandleSet();
        for(String attributeName : _publishAttributeNameSet) {
            try {
                publishedAttributeHandleSet.add(_datamemberNameHandleMap.get("ObjectRoot.ControllerState." + attributeName));
                logger.trace("publish {}:{}", get_class_name(), attributeName);
            } catch (Exception e) {
                logger.error("could not publish \"" + attributeName + "\" attribute.", e);
            }
        }

        synchronized(rti) {
            boolean isNotPublished = true;
            while(isNotPublished) {
                try {
                    rti.publishObjectClass(get_handle(), publishedAttributeHandleSet);
                    isNotPublished = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not publish: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not publish: Object Class Not Defined", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isPublished = true;
        logger.debug("publish: {}", get_class_name());
    }

    /**
    * Unpublishes the ControllerState object class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void unpublish(RTIambassador rti) {
        if (!_isPublished) return;

        init(rti);

        synchronized(rti) {
            boolean isNotUnpublished = true;
            while(isNotUnpublished) {
                try {
                    rti.unpublishObjectClass(get_handle());
                    isNotUnpublished = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not unpublish: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not unpublish: Object Class Not Defined", e);
                    return;
                } catch (ObjectClassNotPublished e) {
                    logger.error("could not unpublish: Object Class Not Published", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isPublished = false;
        logger.debug("unpublish: {}", get_class_name());
    }

    private static boolean _isSubscribed = false;

    /**
    * Subscribes a federate to the ControllerState object class.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void subscribe(RTIambassador rti) {
        if (_isSubscribed) return;

        init(rti);

        AttributeHandleSet subscribedAttributeHandleSet = _factory.createAttributeHandleSet();
        for(String attributeName : _subscribeAttributeNameSet) {
            try {
                subscribedAttributeHandleSet.add(_datamemberNameHandleMap.get("ObjectRoot.ControllerState." + attributeName));
                logger.trace("subscribe {}:{}", get_class_name(), attributeName);
            } catch (Exception e) {
                logger.error("could not subscribe to \"" + attributeName + "\" attribute.", e);
            }
        }

        synchronized(rti) {
            boolean isNotSubscribed = true;
            while(isNotSubscribed) {
                try {
                    rti.subscribeObjectClassAttributes(get_handle(), subscribedAttributeHandleSet);
                    isNotSubscribed = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not subscribe: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not subscribe: Object Class Not Defined", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isSubscribed = true;
        logger.debug("subscribe: {}", get_class_name());
    }

    /**
    * Unsubscribes a federate from the ControllerState object class.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void unsubscribe(RTIambassador rti) {
        if (!_isSubscribed) return;

        init(rti);

        synchronized(rti) {
            boolean isNotUnsubscribed = true;
            while(isNotUnsubscribed) {
                try {
                    rti.unsubscribeObjectClass(get_handle());
                    isNotUnsubscribed = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not unsubscribe: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not unsubscribe: Object Class Not Defined", e);
                    return;
                } catch (ObjectClassNotSubscribed e) {
                    logger.error("could not unsubscribe: Object Class Not Subscribed", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isSubscribed = false;
        logger.debug("unsubscribe: {}", get_class_name());
    }

    /**
    * Return true if "handle" is equal to the handle (RTI assigned) of this class
    * (that is, the ControllerState object class).
    *
    * @param handle handle to compare to the value of the handle (RTI assigned) of
    * this class (the ControllerState object class).
    * @return "true" if "handle" matches the value of the handle of this class
    * (that is, the ControllerState object class).
    */
    public static boolean match(int handle) {
        return handle == get_handle();
    }

    /**
    * Returns the handle (RTI assigned) of this instance's object class .
    *
    * @return the handle (RTI assigned) if this instance's object class
    */
    public int getClassHandle() {
        return get_handle();
    }

    /**
    * Returns the fully-qualified (dot-delimited) name of this instance's object class.
    *
    * @return the fully-qualified (dot-delimited) name of this instance's object class
    */
    public String getClassName() {
        return get_class_name();
    }

    /**
    * Returns the simple name (last name in its fully-qualified dot-delimited name)
    * of this instance's object class.
    *
    * @return the simple name of this instance's object class
    */
    public String getSimpleClassName() {
        return get_simple_class_name();
    }

    /**
    * Returns a set containing the names of all of the non-hiddenattributes of an
    * object class instance.
    *
    * @return set containing the names of all of the attributes of an
    * object class instance
    */
    public Set< String > getAttributeNames() {
        return get_attribute_names();
    }

    /**
    * Returns a set containing the names of all of the attributes of an
    * object class instance.
    *
    * @return set containing the names of all of the attributes of an
    * object class instance
    */
    public Set< String > getAllAttributeNames() {
        return get_all_attribute_names();
    }

    @Override
    public String getAttributeName(int datamemberHandle) {
        if (datamemberHandle == _DamperPostionPct_handle) return "DamperPostionPct";
        else if (datamemberHandle == _ZoneName_handle) return "ZoneName";
        else return super.getAttributeName(datamemberHandle);
    }

    /**
    * Publishes the object class of this instance of the class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public void publishObject(RTIambassador rti) {
        publish(rti);
    }

    /**
    * Unpublishes the object class of this instance of this class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public void unpublishObject(RTIambassador rti) {
        unpublish(rti);
    }

    /**
    * Subscribes a federate to the object class of this instance of this class.
    *
    * @param rti handle to the Local RTI Component
    */
    public void subscribeObject(RTIambassador rti) {
        subscribe(rti);
    }

    /**
    * Unsubscribes a federate from the object class of this instance of this class.
    *
    * @param rti handle to the Local RTI Component
    */
    public void unsubscribeObject(RTIambassador rti) {
        unsubscribe(rti);
    }

    @Override
    public String toString() {
        return getClass().getName() + "("
                + "DamperPostionPct:" + get_DamperPostionPct()
                + "," + "ZoneName:" + get_ZoneName()
                + ")";
    }


    /**
    * Publishes the "DamperPostionPct" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "DamperPostionPct" attribute for publication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void publish_DamperPostionPct() {
        _publishAttributeNameSet.add( "DamperPostionPct" );
    }

    /**
    * Unpublishes the "DamperPostionPct" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "DamperPostionPct" attribute for unpublication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void unpublish_DamperPostionPct() {
        _publishAttributeNameSet.remove( "DamperPostionPct" );
    }

    /**
    * Subscribes a federate to the "DamperPostionPct" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "DamperPostionPct" attribute for subscription.
    * To actually subscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void subscribe_DamperPostionPct() {
        _subscribeAttributeNameSet.add( "DamperPostionPct" );
    }

    /**
    * Unsubscribes a federate from the "DamperPostionPct" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "DamperPostionPct" attribute for unsubscription.
    * To actually unsubscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void unsubscribe_DamperPostionPct() {
        _subscribeAttributeNameSet.remove( "DamperPostionPct" );
    }

    /**
    * Publishes the "ZoneName" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "ZoneName" attribute for publication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void publish_ZoneName() {
        _publishAttributeNameSet.add( "ZoneName" );
    }

    /**
    * Unpublishes the "ZoneName" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "ZoneName" attribute for unpublication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void unpublish_ZoneName() {
        _publishAttributeNameSet.remove( "ZoneName" );
    }

    /**
    * Subscribes a federate to the "ZoneName" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "ZoneName" attribute for subscription.
    * To actually subscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void subscribe_ZoneName() {
        _subscribeAttributeNameSet.add( "ZoneName" );
    }

    /**
    * Unsubscribes a federate from the "ZoneName" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "ZoneName" attribute for unsubscription.
    * To actually unsubscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void unsubscribe_ZoneName() {
        _subscribeAttributeNameSet.remove( "ZoneName" );
    }

    protected Attribute< Integer > _DamperPostionPct =
            new Attribute< Integer >(  new Integer( 0 )  );

    /**
    * Set the value of the "DamperPostionPct" attribute to "value" for this object.
    *
    * @param value the new value for the "DamperPostionPct" attribute
    */
    public void set_DamperPostionPct( int value ) {
        _DamperPostionPct.setValue( value );
        _DamperPostionPct.setTime( getTime() );
    }

    /**
    * Returns the value of the "DamperPostionPct" attribute of this object.
    *
    * @return the value of the "DamperPostionPct" attribute
    */
    public int get_DamperPostionPct() {
        return _DamperPostionPct.getValue();
    }

    /**
    * Returns the current timestamp of the "DamperPostionPct" attribute of this object.
    *
    * @return the current timestamp of the "DamperPostionPct" attribute
    */
    public double get_DamperPostionPct_time() {
        return _DamperPostionPct.getTime();
    }

    protected Attribute< String > _ZoneName =
            new Attribute< String >(  new String( "" )  );

    /**
    * Set the value of the "ZoneName" attribute to "value" for this object.
    *
    * @param value the new value for the "ZoneName" attribute
    */
    public void set_ZoneName( String value ) {
        _ZoneName.setValue( value );
        _ZoneName.setTime( getTime() );
    }

    /**
    * Returns the value of the "ZoneName" attribute of this object.
    *
    * @return the value of the "ZoneName" attribute
    */
    public String get_ZoneName() {
        return _ZoneName.getValue();
    }

    /**
    * Returns the current timestamp of the "ZoneName" attribute of this object.
    *
    * @return the current timestamp of the "ZoneName" attribute
    */
    public double get_ZoneName_time() {
        return _ZoneName.getTime();
    }

    protected ControllerState( ReflectedAttributes datamemberMap, boolean initFlag ) {
        super( datamemberMap, false );
        if ( initFlag ) setAttributes( datamemberMap );
    }

    protected ControllerState( ReflectedAttributes datamemberMap, LogicalTime logicalTime, boolean initFlag ) {
        super( datamemberMap, logicalTime, false );
        if ( initFlag ) setAttributes( datamemberMap );
    }

    /**
    * Creates an instance of the ControllerState object class, using
    * "datamemberMap" to initialize its attribute values.
    * "datamemberMap" is usually acquired as an argument to an RTI federate
    * callback method, such as "receiveInteraction".
    *
    * @param datamemberMap data structure containing initial values for the
    * attributes of this new ControllerState object class instance
    */
    public ControllerState( ReflectedAttributes datamemberMap ) {
        this( datamemberMap, true );
    }

    /**
    * Like {@link #ControllerState( ReflectedAttributes datamemberMap )}, except this
    * new ControllerState object class instance is given a timestamp of
    * "logicalTime".
    *
    * @param datamemberMap data structure containing initial values for the
    * attributes of this new ControllerState object class instance
    * @param logicalTime timestamp for this new ControllerState object class
    * instance
    */
    public ControllerState( ReflectedAttributes datamemberMap, LogicalTime logicalTime ) {
        this( datamemberMap, logicalTime, true );
    }

    /**
    * Creates a new ControllerState object class instance that is a duplicate
    * of the instance referred to by ControllerState_var.
    *
    * @param ControllerState_var ControllerState object class instance of which
    * this newly created ControllerState object class instance will be a
    * duplicate
    */
    public ControllerState( ControllerState ControllerState_var ) {
        super( ControllerState_var );

        set_DamperPostionPct( ControllerState_var.get_DamperPostionPct() );
        set_ZoneName( ControllerState_var.get_ZoneName() );
    }

    /**
    * Returns the value of the attribute whose name is "datamemberName"
    * for this object.
    *
    * @param datamemberName name of attribute whose value is to be
    * returned
    * @return value of the attribute whose name is "datamemberName"
    * for this object
    */
    public Object getAttribute( String datamemberName ) {
        if ( "DamperPostionPct".equals(datamemberName) ) return new Integer(get_DamperPostionPct());
        else if ( "ZoneName".equals(datamemberName) ) return get_ZoneName();
        else return super.getAttribute( datamemberName );
    }

    protected boolean setAttributeAux( String datamemberName, String val ) {
        boolean retval = true;
        if ( "DamperPostionPct".equals( datamemberName) ) set_DamperPostionPct( Integer.parseInt(val) );
        else if ( "ZoneName".equals( datamemberName) ) set_ZoneName( val );
        else retval = super.setAttributeAux( datamemberName, val );

        return retval;
    }

    protected boolean setAttributeAux( String datamemberName, Object val ) {
        boolean retval = true;
        if ( "DamperPostionPct".equals( datamemberName) ) set_DamperPostionPct( (Integer)val );
        else if ( "ZoneName".equals( datamemberName) ) set_ZoneName( (String)val );
        else retval = super.setAttributeAux( datamemberName, val );

        return retval;
    }

    @Override
    protected SuppliedAttributes createSuppliedDatamembers(boolean force) {
        SuppliedAttributes datamembers = _factory.createSuppliedAttributes();
 
        if (_publishAttributeNameSet.contains("DamperPostionPct") && _DamperPostionPct.shouldBeUpdated(force)) {
            datamembers.add( getAttributeHandle("DamperPostionPct"), getAttribute("DamperPostionPct").toString().getBytes() );
            _DamperPostionPct.setHasBeenUpdated();
        }

        if (_publishAttributeNameSet.contains("ZoneName") && _ZoneName.shouldBeUpdated(force)) {
            datamembers.add( getAttributeHandle("ZoneName"), getAttribute("ZoneName").toString().getBytes() );
            _ZoneName.setHasBeenUpdated();
        }

        return datamembers;
    }

    public void copyFrom( Object object ) {
        super.copyFrom( object );
        if ( object instanceof ControllerState ) {
            ControllerState data = (ControllerState)object;
            _DamperPostionPct = data._DamperPostionPct;
            _ZoneName = data._ZoneName;
        }
    }
}

