// This code has been generated by the C2W code generator.
// Do not edit manually!

package HouseProject;

import hla.rti.EventRetractionHandle;
import hla.rti.LogicalTime;
import hla.rti.ReceivedInteraction;

import c2w.hla.C2WInteractionRoot;
import c2w.hla.C2WLogger;
import c2w.hla.InteractionRoot;
import c2w.hla.SubscribedInteractionFilter;
import c2w.hla.SynchronizedFederate;

import c2w.hla.*;


public class HouseBase extends SynchronizedFederate {

    private SubscribedInteractionFilter _subscribedInteractionFilter = new SubscribedInteractionFilter();
    
    // constructor
    public HouseBase( String federation_id, String federate_id ) throws Exception {
    
        setLookahead( 0.2 );
        createRTI();
        joinFederation( federation_id, federate_id );

        enableTimeConstrained();

        enableTimeRegulation( getLookahead() );
        enableAsynchronousDelivery();
        // interaction pubsub
        
        ResourcePhysicalState.publish( getRTI() );
        
        SimTime.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
            SimTime.get_handle(), 
            SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
            SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
        );
        Quote.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
            Quote.get_handle(), 
            SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
            SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
        );
        TMYWeather.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
            TMYWeather.get_handle(), 
            SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
            SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
        );        
        // object pubsub
                        }
        
       // constructor
    public HouseBase(  String[] federationInfo ) throws Exception {

        setLookahead( 0.2 );
        createRTI();
        joinFederation( federationInfo[ 0 ], federationInfo[ 1 ] );

        String loglevel = null;
        loglevel = federationInfo[ 2 ];
/*        
        String loglevel = null;
        if(federationInfo.length == 3)
            C2WLogger.init( federationInfo[ 2 ] );
        else if(federationInfo.length > 3)
            C2WLogger.init( federationInfo[ 2 ], federationInfo[ 3 ] );        
        
        if(federationInfo.length == 5)
            loglevel = federationInfo[ 4 ];
*/
        enableTimeConstrained();
        enableTimeRegulation( getLookahead() );
        enableAsynchronousDelivery();

        // interaction pubsub

        ResourcePhysicalState.publish( getRTI() );

        SimTime.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
            SimTime.get_handle(), 
            SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
            SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
        );
        Quote.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
            Quote.get_handle(), 
            SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
            SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
        );
        TMYWeather.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
            TMYWeather.get_handle(), 
            SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
            SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
        );        // object pubsub
                        // enable pubsub log
        if(federationInfo.length  > 2) {
            
            ResourcePhysicalState.enablePublishLog(
                "ResourcePhysicalState",
                "House",
                "NORMAL",
                loglevel);
            
            SimTime.enableSubscribeLog(
                "SimTime",
                "House", 
                "NORMAL", 
                loglevel);
            Quote.enableSubscribeLog(
                "Quote",
                "House", 
                "NORMAL", 
                loglevel);
            TMYWeather.enableSubscribeLog(
                "TMYWeather",
                "House", 
                "NORMAL", 
                loglevel);    
            
            
        }
        
    }
    
    public ResourcePhysicalState create_ResourcePhysicalState() {
       ResourcePhysicalState interaction = new ResourcePhysicalState();
       interaction.set_sourceFed( getFederateId() );
       interaction.set_originFed( getFederateId() );
       return interaction;
    }

    @Override
    public void receiveInteraction(
     int interactionClass, ReceivedInteraction theInteraction, byte[] userSuppliedTag
    ) {
        InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction );
        if ( interactionRoot instanceof C2WInteractionRoot ) {
            
            C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

            // Filter interaction if src/origin fed requirements (if any) are not met
            if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
                return;
            } 
        }
        
        super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag );            
    }

    @Override
    public void receiveInteraction(
     int interactionClass,
     ReceivedInteraction theInteraction,
     byte[] userSuppliedTag,
     LogicalTime theTime,
     EventRetractionHandle retractionHandle
    ) {
        InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction, theTime );
        if ( interactionRoot instanceof C2WInteractionRoot ) {

            C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

            // Filter interaction if src/origin fed requirements (if any) are not met
            if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
                return;
            } 
        }

        super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag, theTime, retractionHandle );            
    }
}
