// This file was generated by the WebGME Federates Exporter plugin. Do not edit manually!

package HelloWorld;

import java.util.HashSet;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.cpswt.utils.CpswtUtils;

import hla.rti.AttributeHandleSet;
import hla.rti.FederateNotExecutionMember;
import hla.rti.LogicalTime;
import hla.rti.NameNotFound;
import hla.rti.ObjectClassNotDefined;
import hla.rti.ObjectClassNotPublished;
import hla.rti.ObjectClassNotSubscribed;
import hla.rti.RTIambassador;
import hla.rti.ReflectedAttributes;
import hla.rti.SuppliedAttributes;

import org.cpswt.hla.*;

/**
* Implements ObjectRoot.PingCount
*/
public class PingCount extends ObjectRoot {

    private static final Logger logger = LogManager.getLogger();

    /**
    * Creates an instance of the PingCount object class with default attribute values.
    */
    public PingCount() {}

    private static int _RunningCount_handle;
    private static int _SinkName_handle;

    private static boolean _isInitialized = false;

    private static int _handle;

    /**
    * Returns the handle (RTI assigned) of the PingCount object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return the handle of the class pertaining to the reference,
    * rather than the handle of the class for the instance referred to by the reference.
    * For the polymorphic version of this method, use {@link #getClassHandle()}.
    *
    * @return the RTI assigned integer handle that represents this object class
    */
    public static int get_handle() {
        return _handle;
    }

    /**
    * Returns the fully-qualified (dot-delimited) name of the PingCount object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return the name of the class pertaining to the reference,
    * rather than the name of the class for the instance referred to by the reference.
    * For the polymorphic version of this method, use {@link #getClassName()}.
    *
    * @return the fully-qualified HLA class path for this object class
    */
    public static String get_class_name() {
        return "ObjectRoot.PingCount";
    }

    /**
    * Returns the simple name (the last name in the dot-delimited fully-qualified
    * class name) of the PingCount object class.
    *
    * @return the name of this object class
    */
    public static String get_simple_class_name() {
        return "PingCount";
    }

    private static Set< String > _datamemberNames = new HashSet< String >();
    private static Set< String > _allDatamemberNames = new HashSet< String >();

    /**
    * Returns a set containing the names of all of the non-hidden attributes in the
    * PingCount object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return a set of parameter names pertaining to the reference,
    * rather than the parameter names of the class for the instance referred to by
    * the reference.  For the polymorphic version of this method, use
    * {@link #getAttributeNames()}.
    *
    * @return a modifiable set of the non-hidden attribute names for this object class
    */
    public static Set< String > get_attribute_names() {
        return new HashSet< String >(_datamemberNames);
    }

    /**
    * Returns a set containing the names of all of the attributes in the
    * PingCount object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return a set of parameter names pertaining to the reference,
    * rather than the parameter names of the class for the instance referred to by
    * the reference.  For the polymorphic version of this method, use
    * {@link #getAttributeNames()}.
    *
    * @return a modifiable set of the attribute names for this object class
    */
    public static Set< String > get_all_attribute_names() {
        return new HashSet< String >(_allDatamemberNames);
    }

    private static Set< String > _publishAttributeNameSet = new HashSet< String >();
    private static Set< String > _subscribeAttributeNameSet = new HashSet< String >();

    static {
        _classNameSet.add("ObjectRoot.PingCount");
        _classNameClassMap.put("ObjectRoot.PingCount", PingCount.class);

        _datamemberClassNameSetMap.put("ObjectRoot.PingCount", _datamemberNames);
        _allDatamemberClassNameSetMap.put("ObjectRoot.PingCount", _allDatamemberNames);

        _datamemberNames.add("RunningCount");
        _datamemberNames.add("SinkName");

        _datamemberTypeMap.put("RunningCount", "int");
        _datamemberTypeMap.put("SinkName", "String");

        _allDatamemberNames.add("RunningCount");
        _allDatamemberNames.add("SinkName");

        _classNamePublishAttributeNameMap.put("ObjectRoot.PingCount", _publishAttributeNameSet);
        _classNameSubscribeAttributeNameMap.put("ObjectRoot.PingCount", _subscribeAttributeNameSet);
    }

    protected static void init(RTIambassador rti) {
        if (_isInitialized) return;
        _isInitialized = true;

        ObjectRoot.init(rti);

        boolean isNotInitialized = true;
        while(isNotInitialized) {
            try {
                _handle = rti.getObjectClassHandle("ObjectRoot.PingCount");
                isNotInitialized = false;
            } catch (FederateNotExecutionMember e) {
                logger.error("could not initialize: Federate Not Execution Member", e);
                return;
            } catch (NameNotFound e) {
                logger.error("could not initialize: Name Not Found", e);
                return;
            } catch (Exception e) {
                logger.error(e);
                CpswtUtils.sleepDefault();
            }
        }

        _classNameHandleMap.put("ObjectRoot.PingCount", get_handle());
        _classHandleNameMap.put(get_handle(), "ObjectRoot.PingCount");
        _classHandleSimpleNameMap.put(get_handle(), "PingCount");

        isNotInitialized = true;
        while(isNotInitialized) {
            try {
                _RunningCount_handle = rti.getAttributeHandle("RunningCount", get_handle());
                _SinkName_handle = rti.getAttributeHandle("SinkName", get_handle());
                isNotInitialized = false;
            } catch (FederateNotExecutionMember e) {
                logger.error("could not initialize: Federate Not Execution Member", e);
                return;
            } catch (ObjectClassNotDefined e) {
                logger.error("could not initialize: Object Class Not Defined", e);
                return;
            } catch (NameNotFound e) {
                logger.error("could not initialize: Name Not Found", e);
                return;
            } catch (Exception e) {
                logger.error(e);
                CpswtUtils.sleepDefault();
            }
        }

        _datamemberNameHandleMap.put("ObjectRoot.PingCount.RunningCount", _RunningCount_handle);
        _datamemberNameHandleMap.put("ObjectRoot.PingCount.SinkName", _SinkName_handle);

        _datamemberHandleNameMap.put(_RunningCount_handle, "RunningCount");
        _datamemberHandleNameMap.put(_SinkName_handle, "SinkName");
    }

    private static boolean _isPublished = false;

    /**
    * Publishes the PingCount object class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void publish(RTIambassador rti) {
        if (_isPublished) return;

        init(rti);

        AttributeHandleSet publishedAttributeHandleSet = _factory.createAttributeHandleSet();
        for(String attributeName : _publishAttributeNameSet) {
            try {
                publishedAttributeHandleSet.add(_datamemberNameHandleMap.get("ObjectRoot.PingCount." + attributeName));
                logger.trace("publish {}:{}", get_class_name(), attributeName);
            } catch (Exception e) {
                logger.error("could not publish \"" + attributeName + "\" attribute.", e);
            }
        }

        synchronized(rti) {
            boolean isNotPublished = true;
            while(isNotPublished) {
                try {
                    rti.publishObjectClass(get_handle(), publishedAttributeHandleSet);
                    isNotPublished = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not publish: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not publish: Object Class Not Defined", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isPublished = true;
        logger.debug("publish: {}", get_class_name());
    }

    /**
    * Unpublishes the PingCount object class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void unpublish(RTIambassador rti) {
        if (!_isPublished) return;

        init(rti);

        synchronized(rti) {
            boolean isNotUnpublished = true;
            while(isNotUnpublished) {
                try {
                    rti.unpublishObjectClass(get_handle());
                    isNotUnpublished = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not unpublish: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not unpublish: Object Class Not Defined", e);
                    return;
                } catch (ObjectClassNotPublished e) {
                    logger.error("could not unpublish: Object Class Not Published", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isPublished = false;
        logger.debug("unpublish: {}", get_class_name());
    }

    private static boolean _isSubscribed = false;

    /**
    * Subscribes a federate to the PingCount object class.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void subscribe(RTIambassador rti) {
        if (_isSubscribed) return;

        init(rti);

        AttributeHandleSet subscribedAttributeHandleSet = _factory.createAttributeHandleSet();
        for(String attributeName : _subscribeAttributeNameSet) {
            try {
                subscribedAttributeHandleSet.add(_datamemberNameHandleMap.get("ObjectRoot.PingCount." + attributeName));
                logger.trace("subscribe {}:{}", get_class_name(), attributeName);
            } catch (Exception e) {
                logger.error("could not subscribe to \"" + attributeName + "\" attribute.", e);
            }
        }

        synchronized(rti) {
            boolean isNotSubscribed = true;
            while(isNotSubscribed) {
                try {
                    rti.subscribeObjectClassAttributes(get_handle(), subscribedAttributeHandleSet);
                    isNotSubscribed = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not subscribe: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not subscribe: Object Class Not Defined", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isSubscribed = true;
        logger.debug("subscribe: {}", get_class_name());
    }

    /**
    * Unsubscribes a federate from the PingCount object class.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void unsubscribe(RTIambassador rti) {
        if (!_isSubscribed) return;

        init(rti);

        synchronized(rti) {
            boolean isNotUnsubscribed = true;
            while(isNotUnsubscribed) {
                try {
                    rti.unsubscribeObjectClass(get_handle());
                    isNotUnsubscribed = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not unsubscribe: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not unsubscribe: Object Class Not Defined", e);
                    return;
                } catch (ObjectClassNotSubscribed e) {
                    logger.error("could not unsubscribe: Object Class Not Subscribed", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isSubscribed = false;
        logger.debug("unsubscribe: {}", get_class_name());
    }

    /**
    * Return true if "handle" is equal to the handle (RTI assigned) of this class
    * (that is, the PingCount object class).
    *
    * @param handle handle to compare to the value of the handle (RTI assigned) of
    * this class (the PingCount object class).
    * @return "true" if "handle" matches the value of the handle of this class
    * (that is, the PingCount object class).
    */
    public static boolean match(int handle) {
        return handle == get_handle();
    }

    /**
    * Returns the handle (RTI assigned) of this instance's object class .
    *
    * @return the handle (RTI assigned) if this instance's object class
    */
    public int getClassHandle() {
        return get_handle();
    }

    /**
    * Returns the fully-qualified (dot-delimited) name of this instance's object class.
    *
    * @return the fully-qualified (dot-delimited) name of this instance's object class
    */
    public String getClassName() {
        return get_class_name();
    }

    /**
    * Returns the simple name (last name in its fully-qualified dot-delimited name)
    * of this instance's object class.
    *
    * @return the simple name of this instance's object class
    */
    public String getSimpleClassName() {
        return get_simple_class_name();
    }

    /**
    * Returns a set containing the names of all of the non-hiddenattributes of an
    * object class instance.
    *
    * @return set containing the names of all of the attributes of an
    * object class instance
    */
    public Set< String > getAttributeNames() {
        return get_attribute_names();
    }

    /**
    * Returns a set containing the names of all of the attributes of an
    * object class instance.
    *
    * @return set containing the names of all of the attributes of an
    * object class instance
    */
    public Set< String > getAllAttributeNames() {
        return get_all_attribute_names();
    }

    @Override
    public String getAttributeName(int datamemberHandle) {
        if (datamemberHandle == _RunningCount_handle) return "RunningCount";
        else if (datamemberHandle == _SinkName_handle) return "SinkName";
        else return super.getAttributeName(datamemberHandle);
    }

    /**
    * Publishes the object class of this instance of the class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public void publishObject(RTIambassador rti) {
        publish(rti);
    }

    /**
    * Unpublishes the object class of this instance of this class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public void unpublishObject(RTIambassador rti) {
        unpublish(rti);
    }

    /**
    * Subscribes a federate to the object class of this instance of this class.
    *
    * @param rti handle to the Local RTI Component
    */
    public void subscribeObject(RTIambassador rti) {
        subscribe(rti);
    }

    /**
    * Unsubscribes a federate from the object class of this instance of this class.
    *
    * @param rti handle to the Local RTI Component
    */
    public void unsubscribeObject(RTIambassador rti) {
        unsubscribe(rti);
    }

    @Override
    public String toString() {
        return getClass().getName() + "("
                + "RunningCount:" + get_RunningCount()
                + "," + "SinkName:" + get_SinkName()
                + ")";
    }


    /**
    * Publishes the "RunningCount" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "RunningCount" attribute for publication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void publish_RunningCount() {
        _publishAttributeNameSet.add( "RunningCount" );
    }

    /**
    * Unpublishes the "RunningCount" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "RunningCount" attribute for unpublication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void unpublish_RunningCount() {
        _publishAttributeNameSet.remove( "RunningCount" );
    }

    /**
    * Subscribes a federate to the "RunningCount" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "RunningCount" attribute for subscription.
    * To actually subscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void subscribe_RunningCount() {
        _subscribeAttributeNameSet.add( "RunningCount" );
    }

    /**
    * Unsubscribes a federate from the "RunningCount" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "RunningCount" attribute for unsubscription.
    * To actually unsubscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void unsubscribe_RunningCount() {
        _subscribeAttributeNameSet.remove( "RunningCount" );
    }

    /**
    * Publishes the "SinkName" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "SinkName" attribute for publication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void publish_SinkName() {
        _publishAttributeNameSet.add( "SinkName" );
    }

    /**
    * Unpublishes the "SinkName" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "SinkName" attribute for unpublication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void unpublish_SinkName() {
        _publishAttributeNameSet.remove( "SinkName" );
    }

    /**
    * Subscribes a federate to the "SinkName" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "SinkName" attribute for subscription.
    * To actually subscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void subscribe_SinkName() {
        _subscribeAttributeNameSet.add( "SinkName" );
    }

    /**
    * Unsubscribes a federate from the "SinkName" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "SinkName" attribute for unsubscription.
    * To actually unsubscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void unsubscribe_SinkName() {
        _subscribeAttributeNameSet.remove( "SinkName" );
    }

    protected Attribute< Integer > _RunningCount =
            new Attribute< Integer >(  new Integer( 0 )  );

    /**
    * Set the value of the "RunningCount" attribute to "value" for this object.
    *
    * @param value the new value for the "RunningCount" attribute
    */
    public void set_RunningCount( int value ) {
        _RunningCount.setValue( value );
        _RunningCount.setTime( getTime() );
    }

    /**
    * Returns the value of the "RunningCount" attribute of this object.
    *
    * @return the value of the "RunningCount" attribute
    */
    public int get_RunningCount() {
        return _RunningCount.getValue();
    }

    /**
    * Returns the current timestamp of the "RunningCount" attribute of this object.
    *
    * @return the current timestamp of the "RunningCount" attribute
    */
    public double get_RunningCount_time() {
        return _RunningCount.getTime();
    }

    protected Attribute< String > _SinkName =
            new Attribute< String >(  new String( "" )  );

    /**
    * Set the value of the "SinkName" attribute to "value" for this object.
    *
    * @param value the new value for the "SinkName" attribute
    */
    public void set_SinkName( String value ) {
        _SinkName.setValue( value );
        _SinkName.setTime( getTime() );
    }

    /**
    * Returns the value of the "SinkName" attribute of this object.
    *
    * @return the value of the "SinkName" attribute
    */
    public String get_SinkName() {
        return _SinkName.getValue();
    }

    /**
    * Returns the current timestamp of the "SinkName" attribute of this object.
    *
    * @return the current timestamp of the "SinkName" attribute
    */
    public double get_SinkName_time() {
        return _SinkName.getTime();
    }

    protected PingCount( ReflectedAttributes datamemberMap, boolean initFlag ) {
        super( datamemberMap, false );
        if ( initFlag ) setAttributes( datamemberMap );
    }

    protected PingCount( ReflectedAttributes datamemberMap, LogicalTime logicalTime, boolean initFlag ) {
        super( datamemberMap, logicalTime, false );
        if ( initFlag ) setAttributes( datamemberMap );
    }

    /**
    * Creates an instance of the PingCount object class, using
    * "datamemberMap" to initialize its attribute values.
    * "datamemberMap" is usually acquired as an argument to an RTI federate
    * callback method, such as "receiveInteraction".
    *
    * @param datamemberMap data structure containing initial values for the
    * attributes of this new PingCount object class instance
    */
    public PingCount( ReflectedAttributes datamemberMap ) {
        this( datamemberMap, true );
    }

    /**
    * Like {@link #PingCount( ReflectedAttributes datamemberMap )}, except this
    * new PingCount object class instance is given a timestamp of
    * "logicalTime".
    *
    * @param datamemberMap data structure containing initial values for the
    * attributes of this new PingCount object class instance
    * @param logicalTime timestamp for this new PingCount object class
    * instance
    */
    public PingCount( ReflectedAttributes datamemberMap, LogicalTime logicalTime ) {
        this( datamemberMap, logicalTime, true );
    }

    /**
    * Creates a new PingCount object class instance that is a duplicate
    * of the instance referred to by PingCount_var.
    *
    * @param PingCount_var PingCount object class instance of which
    * this newly created PingCount object class instance will be a
    * duplicate
    */
    public PingCount( PingCount PingCount_var ) {
        super( PingCount_var );

        set_RunningCount( PingCount_var.get_RunningCount() );
        set_SinkName( PingCount_var.get_SinkName() );
    }

    /**
    * Returns the value of the attribute whose name is "datamemberName"
    * for this object.
    *
    * @param datamemberName name of attribute whose value is to be
    * returned
    * @return value of the attribute whose name is "datamemberName"
    * for this object
    */
    public Object getAttribute( String datamemberName ) {
        if ( "RunningCount".equals(datamemberName) ) return new Integer(get_RunningCount());
        else if ( "SinkName".equals(datamemberName) ) return get_SinkName();
        else return super.getAttribute( datamemberName );
    }

    protected boolean setAttributeAux( String datamemberName, String val ) {
        boolean retval = true;
        if ( "RunningCount".equals( datamemberName) ) set_RunningCount( Integer.parseInt(val) );
        else if ( "SinkName".equals( datamemberName) ) set_SinkName( val );
        else retval = super.setAttributeAux( datamemberName, val );

        return retval;
    }

    protected boolean setAttributeAux( String datamemberName, Object val ) {
        boolean retval = true;
        if ( "RunningCount".equals( datamemberName) ) set_RunningCount( (Integer)val );
        else if ( "SinkName".equals( datamemberName) ) set_SinkName( (String)val );
        else retval = super.setAttributeAux( datamemberName, val );

        return retval;
    }

    @Override
    protected SuppliedAttributes createSuppliedDatamembers(boolean force) {
        SuppliedAttributes datamembers = _factory.createSuppliedAttributes();
 
        if (_publishAttributeNameSet.contains("RunningCount") && _RunningCount.shouldBeUpdated(force)) {
            datamembers.add( getAttributeHandle("RunningCount"), getAttribute("RunningCount").toString().getBytes() );
            _RunningCount.setHasBeenUpdated();
        }

        if (_publishAttributeNameSet.contains("SinkName") && _SinkName.shouldBeUpdated(force)) {
            datamembers.add( getAttributeHandle("SinkName"), getAttribute("SinkName").toString().getBytes() );
            _SinkName.setHasBeenUpdated();
        }

        return datamembers;
    }

    public void copyFrom( Object object ) {
        super.copyFrom( object );
        if ( object instanceof PingCount ) {
            PingCount data = (PingCount)object;
            _RunningCount = data._RunningCount;
            _SinkName = data._SinkName;
        }
    }
}

